// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: auditlog.proto

package auditlog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuditLog 审计日志实体。
type AuditLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 日志主键，UUIDv7，为空时服务端自动生成。
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 链路追踪 ID。
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 产生日志的服务名。
	ServiceName string `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// 具体操作（方法/接口路径），如 POST /api/v1/users。
	Operation string `protobuf:"bytes,4,opt,name=operation,proto3" json:"operation,omitempty"`
	// 操作者 ID。
	ActorId string `protobuf:"bytes,5,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	// 操作者类型，如 user / service / admin。
	ActorType string `protobuf:"bytes,6,opt,name=actor_type,json=actorType,proto3" json:"actor_type,omitempty"`
	// 动作类型，如 CREATE / UPDATE / DELETE / LOGIN / QUERY。
	Action string `protobuf:"bytes,7,opt,name=action,proto3" json:"action,omitempty"`
	// 资源类型，如 order / user。
	ResourceType string `protobuf:"bytes,8,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// 资源 ID。
	ResourceId string `protobuf:"bytes,9,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// 来源 IP。
	SourceIp string `protobuf:"bytes,10,opt,name=source_ip,json=sourceIp,proto3" json:"source_ip,omitempty"`
	// User-Agent。
	UserAgent string `protobuf:"bytes,11,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	// 请求 URI。
	RequestUri string `protobuf:"bytes,12,opt,name=request_uri,json=requestUri,proto3" json:"request_uri,omitempty"`
	// 业务状态码。
	StatusCode int32 `protobuf:"varint,13,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	// 请求体（脱敏后存储）。
	RequestBody string `protobuf:"bytes,14,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	// 响应体（脱敏后存储）。
	ResponseBody string `protobuf:"bytes,15,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	// 扩展元数据，JSON 字符串。
	Metadata string `protobuf:"bytes,16,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// 错误信息。
	ErrorMessage string `protobuf:"bytes,17,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// 耗时（毫秒）。
	DurationMs int64 `protobuf:"varint,18,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// 创建时间，Unix 毫秒时间戳，由服务端填充。
	CreatedAt     int64 `protobuf:"varint,19,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_auditlog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_auditlog_proto_rawDescGZIP(), []int{0}
}

func (x *AuditLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditLog) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AuditLog) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *AuditLog) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *AuditLog) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditLog) GetActorType() string {
	if x != nil {
		return x.ActorType
	}
	return ""
}

func (x *AuditLog) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditLog) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *AuditLog) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *AuditLog) GetSourceIp() string {
	if x != nil {
		return x.SourceIp
	}
	return ""
}

func (x *AuditLog) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuditLog) GetRequestUri() string {
	if x != nil {
		return x.RequestUri
	}
	return ""
}

func (x *AuditLog) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AuditLog) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *AuditLog) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *AuditLog) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *AuditLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuditLog) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *AuditLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

// CreateAuditLogsRequest 批量写入审计日志请求，支持一条或多条。
type CreateAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*AuditLog            `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditLogsRequest) Reset() {
	*x = CreateAuditLogsRequest{}
	mi := &file_auditlog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditLogsRequest) ProtoMessage() {}

func (x *CreateAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*CreateAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_auditlog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAuditLogsRequest) GetLogs() []*AuditLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type CreateAuditLogsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 写入成功的日志 ID 列表，顺序与请求一致。
	Ids           []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuditLogsResponse) Reset() {
	*x = CreateAuditLogsResponse{}
	mi := &file_auditlog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuditLogsResponse) ProtoMessage() {}

func (x *CreateAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*CreateAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_auditlog_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAuditLogsResponse) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

// SearchAuditLogsRequest 审计日志分页查询请求，所有过滤条件均可选。
type SearchAuditLogsRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	ServiceName  string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ActorId      string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Action       string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ResourceType string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	ResourceId   string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TraceId      string                 `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// 起始时间，Unix 毫秒。
	StartTime int64 `protobuf:"varint,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// 结束时间，Unix 毫秒。
	EndTime int64 `protobuf:"varint,8,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// 页码，从 1 开始，默认 1。
	Page int64 `protobuf:"varint,9,opt,name=page,proto3" json:"page,omitempty"`
	// 每页大小，默认 20，最大 200。
	PageSize      int64 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAuditLogsRequest) Reset() {
	*x = SearchAuditLogsRequest{}
	mi := &file_auditlog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAuditLogsRequest) ProtoMessage() {}

func (x *SearchAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*SearchAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_auditlog_proto_rawDescGZIP(), []int{3}
}

func (x *SearchAuditLogsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SearchAuditLogsRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *SearchAuditLogsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SearchAuditLogsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *SearchAuditLogsRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *SearchAuditLogsRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *SearchAuditLogsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SearchAuditLogsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SearchAuditLogsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchAuditLogsRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SearchAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*AuditLog            `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAuditLogsResponse) Reset() {
	*x = SearchAuditLogsResponse{}
	mi := &file_auditlog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAuditLogsResponse) ProtoMessage() {}

func (x *SearchAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auditlog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*SearchAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_auditlog_proto_rawDescGZIP(), []int{4}
}

func (x *SearchAuditLogsResponse) GetList() []*AuditLog {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SearchAuditLogsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_auditlog_proto protoreflect.FileDescriptor

const file_auditlog_proto_rawDesc = "" +
	"\n" +
	"\x0eauditlog.proto\x12\bauditlog\"\xd5\x04\n" +
	"\bAuditLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1c\n" +
	"\toperation\x18\x04 \x01(\tR\toperation\x12\x19\n" +
	"\bactor_id\x18\x05 \x01(\tR\aactorId\x12\x1d\n" +
	"\n" +
	"actor_type\x18\x06 \x01(\tR\tactorType\x12\x16\n" +
	"\x06action\x18\a \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\b \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\t \x01(\tR\n" +
	"resourceId\x12\x1b\n" +
	"\tsource_ip\x18\n" +
	" \x01(\tR\bsourceIp\x12\x1d\n" +
	"\n" +
	"user_agent\x18\v \x01(\tR\tuserAgent\x12\x1f\n" +
	"\vrequest_uri\x18\f \x01(\tR\n" +
	"requestUri\x12\x1f\n" +
	"\vstatus_code\x18\r \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\frequest_body\x18\x0e \x01(\tR\vrequestBody\x12#\n" +
	"\rresponse_body\x18\x0f \x01(\tR\fresponseBody\x12\x1a\n" +
	"\bmetadata\x18\x10 \x01(\tR\bmetadata\x12#\n" +
	"\rerror_message\x18\x11 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vduration_ms\x18\x12 \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"created_at\x18\x13 \x01(\x03R\tcreatedAt\"@\n" +
	"\x16CreateAuditLogsRequest\x12&\n" +
	"\x04logs\x18\x01 \x03(\v2\x12.auditlog.AuditLogR\x04logs\"+\n" +
	"\x17CreateAuditLogsResponse\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"\xba\x02\n" +
	"\x16SearchAuditLogsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\b \x01(\x03R\aendTime\x12\x12\n" +
	"\x04page\x18\t \x01(\x03R\x04page\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x03R\bpageSize\"W\n" +
	"\x17SearchAuditLogsResponse\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.auditlog.AuditLogR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total2\xc1\x01\n" +
	"\x0fAuditLogService\x12V\n" +
	"\x0fCreateAuditLogs\x12 .auditlog.CreateAuditLogsRequest\x1a!.auditlog.CreateAuditLogsResponse\x12V\n" +
	"\x0fSearchAuditLogs\x12 .auditlog.SearchAuditLogsRequest\x1a!.auditlog.SearchAuditLogsResponseB-Z+cari.com.cn/framework/auditlog/rpc/auditlogb\x06proto3"

var (
	file_auditlog_proto_rawDescOnce sync.Once
	file_auditlog_proto_rawDescData []byte
)

func file_auditlog_proto_rawDescGZIP() []byte {
	file_auditlog_proto_rawDescOnce.Do(func() {
		file_auditlog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auditlog_proto_rawDesc), len(file_auditlog_proto_rawDesc)))
	})
	return file_auditlog_proto_rawDescData
}

var file_auditlog_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_auditlog_proto_goTypes = []any{
	(*AuditLog)(nil),                // 0: auditlog.AuditLog
	(*CreateAuditLogsRequest)(nil),  // 1: auditlog.CreateAuditLogsRequest
	(*CreateAuditLogsResponse)(nil), // 2: auditlog.CreateAuditLogsResponse
	(*SearchAuditLogsRequest)(nil),  // 3: auditlog.SearchAuditLogsRequest
	(*SearchAuditLogsResponse)(nil), // 4: auditlog.SearchAuditLogsResponse
}
var file_auditlog_proto_depIdxs = []int32{
	0, // 0: auditlog.CreateAuditLogsRequest.logs:type_name -> auditlog.AuditLog
	0, // 1: auditlog.SearchAuditLogsResponse.list:type_name -> auditlog.AuditLog
	1, // 2: auditlog.AuditLogService.CreateAuditLogs:input_type -> auditlog.CreateAuditLogsRequest
	3, // 3: auditlog.AuditLogService.SearchAuditLogs:input_type -> auditlog.SearchAuditLogsRequest
	2, // 4: auditlog.AuditLogService.CreateAuditLogs:output_type -> auditlog.CreateAuditLogsResponse
	4, // 5: auditlog.AuditLogService.SearchAuditLogs:output_type -> auditlog.SearchAuditLogsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_auditlog_proto_init() }
func file_auditlog_proto_init() {
	if File_auditlog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auditlog_proto_rawDesc), len(file_auditlog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auditlog_proto_goTypes,
		DependencyIndexes: file_auditlog_proto_depIdxs,
		MessageInfos:      file_auditlog_proto_msgTypes,
	}.Build()
	File_auditlog_proto = out.File
	file_auditlog_proto_goTypes = nil
	file_auditlog_proto_depIdxs = nil
}
